# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_image.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(230, 10, 110, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSave.setFont(font)
        self.btnSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSave.setAutoFillBackground(False)
        self.btnSave.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.btnSave.setObjectName("btnSave")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(230, 130, 110, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnExit.setFont(font)
        self.btnExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnExit.setAutoFillBackground(False)
        self.btnExit.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.btnExit.setObjectName("btnExit")
        self.cbbFolder = QtWidgets.QComboBox(self.centralwidget)
        self.cbbFolder.setGeometry(QtCore.QRect(230, 220, 110, 30))
        self.cbbFolder.setObjectName("cbbFolder")
        self.txtKytu = QtWidgets.QLabel(self.centralwidget)
        self.txtKytu.setGeometry(QtCore.QRect(230, 190, 110, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        self.txtKytu.setFont(font)
        self.txtKytu.setAlignment(QtCore.Qt.AlignCenter)
        self.txtKytu.setObjectName("txtKytu")
        self.txtSoluonganh = QtWidgets.QLabel(self.centralwidget)
        self.txtSoluonganh.setGeometry(QtCore.QRect(230, 260, 110, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        self.txtSoluonganh.setFont(font)
        self.txtSoluonganh.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSoluonganh.setObjectName("txtSoluonganh")
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(230, 70, 110, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnDelete.setFont(font)
        self.btnDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDelete.setAutoFillBackground(False)
        self.btnDelete.setStyleSheet("background-color: rgb(237, 212, 0)")
        self.btnDelete.setObjectName("btnDelete")
        self.txtImgcount = QtWidgets.QLabel(self.centralwidget)
        self.txtImgcount.setGeometry(QtCore.QRect(230, 290, 110, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        self.txtImgcount.setFont(font)
        self.txtImgcount.setAlignment(QtCore.Qt.AlignCenter)
        self.txtImgcount.setObjectName("txtImgcount")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 224, 224))
        self.graphicsView.setObjectName("graphicsView")
        self.btnOnCam = QtWidgets.QPushButton(self.centralwidget)
        self.btnOnCam.setGeometry(QtCore.QRect(30, 240, 161, 61))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnOnCam.setFont(font)
        self.btnOnCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOnCam.setAutoFillBackground(False)
        self.btnOnCam.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.btnOnCam.setObjectName("btnOnCam")
        self.txtImgHand = QtWidgets.QLabel(self.centralwidget)
        self.txtImgHand.setGeometry(QtCore.QRect(0, 0, 224, 224))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(12)
        self.txtImgHand.setFont(font)
        self.txtImgHand.setAlignment(QtCore.Qt.AlignCenter)
        self.txtImgHand.setObjectName("txtImgHand")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSave.setText(_translate("MainWindow", "Lưu ảnh"))
        self.btnExit.setText(_translate("MainWindow", "Thoát"))
        self.txtKytu.setText(_translate("MainWindow", "Ký tự"))
        self.txtSoluonganh.setText(_translate("MainWindow", "Số ảnh"))
        self.btnDelete.setText(_translate("MainWindow", "Xóa ảnh"))
        self.txtImgcount.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ef2929;\">0</span></p></body></html>"))
        self.btnOnCam.setText(_translate("MainWindow", "Bật Camera"))
        self.txtImgHand.setText(_translate("MainWindow", "Ảnh bàn tay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
